; Updated on 2026-05-08 by Steven Orr

[Labels]
author = Author
letterName = Automatic Loans Renew Letter
subject = Automatic Loans Renew Notice
call_number = Call Number
department = Circulation Department
description = Description
due_date = Due Date
additional_info_1 = EMPTY_STRING
additional_info_2 = EMPTY_STRING
library = Library
loans = Loans
location = Location
Cc = None
Bcc = None
renew_status = Renew Status
sincerely = Sincerely
message = The following items have been renewed:
title = Title
addressFrom = Your.Department@organization.com