; Updated on 2026-05-08 by Steven Orr

[Labels]
addressFrom = (null)
notification_sent = A notification will be sent once the resource becomes available.
here = Access Resource
letterName = Delivery Registration Status Report
subject = Delivery Registration Status Report
contact_library = For more information, please contact the library.
registration_status_available = Item Available {0}
register = Join
library = Library
cc = None
bcc = None
once_started_viewing = Once started viewing, 
registration_status_confirmation = Registration Confirmation {0}
registration_status_expired = Registration Grace Period Expired {0}
registration_status_removed = Registration canceled {0}
department = Resource Management Department
sincerely = Sincerely
status = Status
title = Title
time_accessing = Unfortunately your availability window for accessing
you_can_reregister = You can re-join to the waitlist.
you_have = You have
register_successfully = You have been added to the waitlist for accessing
removed = You have been removed from the waitlist for accessing
hold_expire = You may need to register again if the hold time expires.
you_will_have = You will have
current_queue_position = and are currently number
has_expired = has expired.
in_queue = in the waitlist.
item_available = is now available for you.
minutes = minute(s).
within_minutes = minutes to start viewing the resource before it will be passed on to the next user in the waitlist.
to_start_viewing = to start viewing the resource before it will be passed on to the next user in the waitlist.
to_view_resource = to view the resource.
link_to_item = {alma_url}/view/delivery/{instCode}/{repId}