; Updated on 2026-05-08 by Steven Orr

[Labels]
addressFrom = (null)
active_deposits = Active Deposits
click = Click
date_created = Date Created
date_updated = Date Updated
deposit_id = Deposit ID
letterName = Deposit Status Report
subject = Deposit Status Report
reminder_message = Here is a report of your deposit activities:
library = Library
new_deposits = New Deposits
cc = None
bcc = None
department = Resource Management Department
sincerely = Sincerely
status = Status
title = Title
here = here
since = since
access_deposits = to access your deposits.
link_to_deposits = {alma_url}/{instCode}/deposit