; Updated on 2026-05-08 by Steven Orr

[Labels]
subject = <Your Deposit>: deposit_title
department = Alma deposit approval team
deposit_id = Deposit ID is:
letterName = Deposit Status Update
approve_text = None
decline_text = None
withdraw_text = None
return_text = None
submit_text = None
Bcc = None
Cc = None
note = Note:
reason = Reason:
sincerely = Sincerely,
view_deposit = View Deposit
addressFrom = Your Department@organization.com
your_deposit = Your deposit
has_been = has been