; Updated on 2026-05-08 by Steven Orr

[Labels]
addressFrom = (null)
letterName = Download Digital Titles Inventory 
subject = Download digital titles inventory job finished
cc = None
bcc = None
department = Resource Management Department
sincerely = Sincerely
c.pa.email_size_title = Size:
c.pa.email_body2 = The content will be available for download for a week.
c.pa.email_body1 = The digital files you have requested are now available for
link = download.