; Created on 2026-05-08 by Steven Orr

[Labels]
subject = Login using your email address
letterName = Login using your email address
linkNoticeText = Please notice: This link is usable only in the same browser where the login flow started from.
signature = Sincerely,
expirationBodyText = This link will expire in 10 minutes.
bodyTextBeforeLink = To log in,
addressFrom = Your.Department@organization.com
bodyTextAfterLink = and follow the instructions provided.
linkLabel = click here