; Created on 2026-05-08 by Steven Orr

[Labels]
baseFee = Base Fee
chargeAmount = Charge Amount
copyrightFee = Copyright Fee
header = Dear Sir/Madam,
externalIdentifier = External Identifier
feeType = Fee Type
subject = Invoice Letter
invoiceNumber = Invoice Number
pageOverageFee = Page Overage Fee
letterName = Partner Invoice Letter
requestSubtotal = Request Subtotal
requestsTotal = Requests Total
department = Resource Sharing Department
serviceLevelFee = Service Level Fee
shippingCost = Shipping cost
signature = Sincerely
title = Title
addressFrom = Your.Department@organization.com