; Created on 2026-05-08 by Steven Orr

[Labels]
department = Circulation Services
addressFrom = Fresno State Library<library-access-services@mail.fresnostate.edu>
subject = New PIN Number
letterName = PIN Number Letter
sincerely = Sincerely,
pinNumberSetTo = Your PIN number has been set to the following value: