; Updated on 2026-05-08 by Steven Orr

[Labels]
department = Resource Management
format = Format
Bcc = None
Cc = None
enter_query_here = Please enter your query here
addressFrom = Purchasing<datwood@mail.fresnostate.edu>
query_to_requester = Query to requester
letterName = Regarding your purchase request
sincerely = Sincerely,
title = Title
subject = Your request