; Updated on 2026-05-08 by Steven Orr

[Labels]
department = Acquisitions Department
addressFrom = Fresno State Library<library-access-services@mail.fresnostate.edu>
reminder_register_opinion = If you have not yet registered your opinion, please be sure to do so before the end of the trial
Cc = None
Bcc = None
sincerely = Sincerely,
introduction_body_thanks = Thank you for agreeing to participate in the trial we are conducting for
schedule = The trial is scheduled to run from
subject = Trial
letterName = Trial
reminder_end_thanks = We'd like to thank those of you that have already submitted their comments.
linkToCollection = link to Electronic Collection
link = link to trial form