; Updated on 2026-05-08 by Steven Orr

[Labels]
comment = Comment
fee_amount = Fee Amount
fee_owner = Fee Owner
fee_type = Fee Type
addressFrom = Fresno State Library<library-access-services@mail.fresnostate.edu>
Cc = None
Bcc = None
notification_message = Please notice that you have the following active fines/fees:
sincerely = Sincerely,
title = Title
department = User Department
subject = User Notification
letterName = User Notification